# Generated by Django 2.1.2 on 2018-11-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GBP_m15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.IntegerField(default=None)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('open', models.FloatField(default=None)),
                ('high', models.FloatField(default=None)),
                ('low', models.FloatField(default=None)),
                ('close', models.FloatField(default=None)),
                ('chinaTime', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmdata',
        ),
    ]
